version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: ai-chatbot-api
    env_file:
      - ../.env
    environment:
      # 기본값이 없는 필수 env는 여기서도 보강 가능
      - VECTOR_BACKEND=${VECTOR_BACKEND:-faiss}
      - VECTOR_DB=${VECTOR_DB:-/data/chroma}
      - DOCS_DIR=${DOCS_DIR:-/data/docs}
    volumes:
      - ../data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: ai-chatbot-redis
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    restart: unless-stopped
